# Generated by Django 5.1.3 on 2024-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], default='logout', max_length=10),
        ),
    ]
