# Generated by Django 5.1.3 on 2024-12-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrcode_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='empid',
        ),
        migrations.AddField(
            model_name='attendance',
            name='empid_id',
            field=models.CharField(default='EMP00S', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='activity',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], default='logout', max_length=10),
        ),
    ]
