# Generated by Django 5.1.3 on 2024-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_activity_remove_attendance_empid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='QRCode_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
